language: c

matrix:
  include:
  - name: "Standard GCC"
    compiler: gcc
    before_script:
      - mkdir build
      - cd build
      - cmake ..
    script:
      - make

  - name: "Standard Clang"
    compiler: clang
    before_script:
      - mkdir build
      - cd build
      - cmake ..
    script:
      - make

  - name: "Coverage"
    compiler: clang
    os: linux
    addons:
      apt:
        packages:
          - llvm
    script:
      - bash ./scripts/coverage.sh
