language: c

matrix:
  include:
  - name: "Standard GCC"
    compiler: gcc
  - name: "Standard Clang"
    compiler: clang
  - name: "Coverage"
    compiler: clang
    env: COLORIST_COVERAGE=1


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
