language: c

compiler:
  - gcc
  - clang

matrix:
  include:
  - name: "Standard"
    env:
  - name: "Coverage"
    env: COLORIST_COVERAGE=1
  exclude:
  - compiler: gcc
    include:
      name: "Coverage"


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
