image: Visual Studio 2017
configuration: Release

before_build:
  - appveyor DownloadFile "https://github.com/joedrago/nasm_mirror/raw/master/nasm-2.14.02-win64.zip" -FileName "nasm.zip"
  - 7z x "nasm.zip" > nul
  - move nasm-* NASM
  - set PATH=%PATH%;%CD%\NASM;
  - nasm -v

  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -A x64

build:
  project: C:/projects/colorist/build/colorist.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: build\bin\colorist\Release\colorist.exe
  name: colorist.exe
  
deploy:
  - provider: GitHub
    artifact: build\bin\colorist\Release\colorist.exe
    auth_token:
      secure: 'hY5Mk6KOwgQ97TzEBsM7Woqr1ZIm5QTvHg8EvxMV1x8j3wk/3mNBMqWFFbEIBK0i'
    prerelease: true
    on:
      appveyor_repo_tag: true
